### PR TITLE
add versioningit for automatic version numbers

### PR DESCRIPTION
**Pull request by grothe6**

### CODE REVIEW

**Comment by newton-per-sqm** [comment]
_Suggestion_: I would wrap the `version` method into a try-except block, as it can happen that a `PackageNotFoundException` appears if the package is not correctly installed (or used as a local dependency).

It's a standardized way I know from e.g. `setuptools_scm`, a package similar to `versioningit`. And, this would make the build of QuMADA independent from its version number, as 'not knowing the version' should normally not be a showstopper for building the package. 

**MWE**

```python

from importlib.metadata import PackageNotFoundError, version  # pragma: no cover

try:
    # Change here if project is renamed and does not equal the package name
    dist_name = "qumada"
    __version__ = version(dist_name)
except PackageNotFoundError:  # pragma: no cover
    __version__ = "unknown"
finally:
    del version, PackageNotFoundError

```

**Comment by newton-per-sqm** [comment]
_Another Suggestion_: As this change would need the user to have `versioningit` installed before building or installing QuMADA, an appropriate exception add-on should be raised in `setup.py` if it is not. 

**MWE**

```python

from setuptools import setup

if __name__ == "__main__":
    try:
        setup()
    except:  # noqa
        print(
            "\n\nAn error occurred while building the project, "
            "please ensure you have the most updated version of setuptools, "
            "setuptools_scm and wheel with:\n"
            "   pip install -U setuptools setuptools_scm wheel\n\n"
        )
        raise

```

It suffices to use `print` here, so that the user is able to see this statement in addition to the error in stdout.

**Comment by grothe6** [comment]
> _Another Suggestion_: As this change would need the user to have `versioningit` installed before building or installing QuMADA, an appropriate exception add-on should be raised in `setup.py` if it is not.
> 
> **MWE**
> 
> ```python
> from setuptools import setup
> 
> if __name__ == "__main__":
>     try:
>         setup()
>     except:  # noqa
>         print(
>             "\n\nAn error occurred while building the project, "
>             "please ensure you have the most updated version of setuptools, "
>             "versioningit and wheel with:\n"
>             "   pip install -U setuptools versioningit wheel\n\n"
>         )
>         raise
> ```
> 
> It suffices to use `print` here, so that the user is able to see this statement in addition to the error in stdout.

I think this is not necessary. The build system should install the dependencies automatically during the build, see https://setuptools.pypa.io/en/latest/userguide/dependency_management.html



> _Suggestion_: I would wrap the `version` method into a try-except block, as it can happen that a `PackageNotFoundException` appears if the package is not correctly installed (or used as a local dependency).
> 
> It's a standardized way I know from e.g. `setuptools_scm`, a package similar to `versioningit`. And, this would make the build of QuMADA independent from its version number, as 'not knowing the version' should normally not be a showstopper for building the package.
> 
> **MWE**
> 
> ```python
> from importlib.metadata import PackageNotFoundError, version  # pragma: no cover
> 
> try:
>     # Change here if project is renamed and does not equal the package name
>     dist_name = "qumada"
>     __version__ = version(dist_name)
> except PackageNotFoundError:  # pragma: no cover
>     __version__ = "unknown"
> finally:
>     del version, PackageNotFoundError
> ```

This issue would arise, when one tries to build the documentation without having installed qumada beforehand. But in that case, the documentation build would abort either way, so I'm not sure, how useful this addition is.

**Comment by grothe6** [comment]
One thing I came across, though, were outdated version numbers. When installing qumada as editable package, the version number is set. Now development goes on, but the version number stays the same. This affects at least the version number e.g. in `pip list` and building the documentation using make directly, as this does not reinstall qumada. I noticed, that the version number in `pip list` updated after a tox run, but I don't know why.

Other ways to programmatically get the version number are detailed here: https://versioningit.readthedocs.io/en/stable/runtime-version.html, but these may suffer from the same issue.

Looking at QCoDeS, it seems to get the version number dynamically every time, see https://github.com/QCoDeS/Qcodes/blob/master/qcodes/_version.py
As versioningit is a dependency of QCoDeS and installed either way, we could just do the same.

**Comment by newton-per-sqm** [comment]
> I think this is not necessary. The build system should install the dependencies automatically during the build, see https://setuptools.pypa.io/en/latest/userguide/dependency_management.html

Interesting, it already happened to me once, not in this case here but in another repo.

**Comment by newton-per-sqm** [comment]
> This issue would arise, when one tries to build the documentation without having installed qumada beforehand. But in that case, **the documentation build would abort either way, so I'm not sure, how useful this addition is.
**

I'm not sure wether it would abort immediately, as the package would be available as local dependency? But yes, if your tox workflow is written correctly, this issue should not arise.

**Comment by newton-per-sqm** [comment]
> I noticed, that the version number in pip list updated after a tox run, but I don't know why.

IMHO `tox` always re-creates its environment, in minimum by reinstalling the project package. This should always update the package version in pip. Pip itself is not tracking the version of your install, only on updates/reinstalls?

**Comment by grothe6** [comment]
> > This issue would arise, when one tries to build the documentation without having installed qumada beforehand. But in that case, **the documentation build would abort either way, so I'm not sure, how useful this addition is.
> > **
> 
> I'm not sure wether it would abort immediately, as the package would be available as local dependency? But yes, if your tox workflow is written correctly, this issue should not arise.

It's because we use autopackagesummary to document qumada in [docs/qumada.rst](https://github.com/qutech/QuMADA/blob/main/docs/qumada.rst). When the package is not available, it fails.

**Comment by grothe6** [comment]
> Looking at QCoDeS, it seems to get the version number dynamically every time, see https://github.com/QCoDeS/Qcodes/blob/master/qcodes/_version.py As versioningit is a dependency of QCoDeS and installed either way, we could just do the same.

Apparently, QCoDeS does get the version number dynamically only, when the package is installed editable. When installing or building from source / wheel, versioningit replaces `__version__` with a fixed string. This solves our issue with outdated version numbers and so I would just do the same for QuMADA.

More info here:
- https://github.com/jwodder/versioningit/issues/8
- https://versioningit.readthedocs.io/en/stable/configuration.html#onbuild

**Pull request merged**
