### PR TITLE
Hotfixes

### PR DESCRIPTION
**Pull request by THuckemann**
Just some minor import related fixes to make everything work

### CODE REVIEW

**Comment by THuckemann** [comment]
Not sure why the Unit Test fails. I had to add the undescore in front of _catch_interrupts as this was apparently changed in QCodes some time ago (could not find it in the changelog though), it works fine on all setups I use. Maybe a different Qcodes Version is used for the tests?

**Comment by newton-per-sqm** [comment]
The unit-tests say:

```
ERROR src/tests/instrument_test.py - TypeError: getfixtureclosure() got an unexpected keyword argument 'initialnames'
ERROR src/tests/mapping_test.py
ERROR src/tests/metadata_test.py - TypeError: getfixtureclosure() got an unexpected keyword argument 'initialnames'
```

**Comment by newton-per-sqm** [comment]
Conceptionally, such CI flows are always build with new environment setups. Your pytest environment is using qcpdes >= 0.40, so always the newest published version:

```
Collecting qcodes>=0.40.0 (from QuMADA==0.4.2.post82+ge9eae12)
  Downloading qcodes-0.44.0-py3-none-any.whl.metadata (9.2 kB)
```

**Comment by THuckemann** [comment]
> @THuckemann: Could you check the files mentioned in my previous comment ([#70 (comment)](https://github.com/qutech/QuMADA/pull/70#issuecomment-1931605850)) wether they are working on your setup?

They all work (after installing pytest and related modules).
Also I would put more focus on this part of the test report, as renaming catch_interrupts to _catch_interrupts was one of the changes in the last commit. I could try to do the import with a try/except to cover the old import without an underscore to pinpoint the problem.

ImportError while importing test module '/home/runner/work/QuMADA/QuMADA/src/tests/mapping_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/tests/mapping_test.py:50: in <module>
    from qumada.measurement.scripts.generic_measurement import Generic_1D_Sweep
src/qumada/measurement/scripts/__init__.py:21: in <module>
    from .generic_measurement import (
src/qumada/measurement/scripts/generic_measurement.py:33: in <module>
    from qumada.measurement.doNd_enhanced.doNd_enhanced import (
src/qumada/measurement/doNd_enhanced/doNd_enhanced.py:43: in <module>
    from qcodes.dataset.dond.do_nd_utils import (
E   ImportError: cannot import name '_catch_interrupts' from 'qcodes.dataset.dond.do_nd_utils' (/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/qcodes/dataset/dond/do_nd_utils.py)

**Comment by THuckemann** [comment]
Ok, this didnt solve the problem, although the import related part disappeared from the log. 
I presume this is just an issue with pytest 8.0.0 then (see [here](https://github.com/pytest-dev/pytest/issues/11868)).
Can we downgrade to the previous version until this is resolved?

**Comment by THuckemann** [comment]
The import issue still remains, but at least we can bypass it with the current try except block. I will commit the merge now as the hotfixes are required to make the current version work.

**Pull request merged**
